version: "3.3"
services:
  react-app:
    build: ./client
    restart: always
    depends_on:
      - server
    ports:
      - "3000:3000"
  server:
    build: ./server
    restart: always
    links:
      - postgres
    ports:
      - "9000:9000"
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/10-init.sql
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: vs2AMBjvnGQLr75Q
      POSTGRES_DB: shop
